# PVF-MCP Installer for Windows
# ================================
# Zero-dependency installer. PowerShell 5.1+ (built into Windows 10/11).
#
# Usage:
#   .\install.ps1                           Auto-detect AI tools
#   .\install.ps1 -Target claude            Claude Code only
#   .\install.ps1 -Target cursor            Cursor only
#   .\install.ps1 -Target codex             Codex only
#   .\install.ps1 -Target all               All detected
#   .\install.ps1 -Target generic -ConfigPath "C:\path\mcp.json"
#
# Generated by PVF-MCP project

param(
    [ValidateSet("claude", "cursor", "codex", "all", "generic")]
    [string]$Target,

    [string]$ConfigPath,

    [string]$InstallDir
)

$ErrorActionPreference = "Stop"
$Host.UI.RawUI.WindowTitle = "PVF-MCP Installer"

Write-Host "PVF-MCP Installation" -ForegroundColor Cyan
Write-Host "====================" -ForegroundColor Cyan

# ---- Locate binary ----
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BinaryName = "pvf-mcp.exe"
$BinarySrc = Join-Path $ScriptDir $BinaryName

if (-not (Test-Path $BinarySrc)) {
    Write-Host "[ERROR] Binary not found: $BinarySrc" -ForegroundColor Red
    Write-Host "Build first: cd PVF-MCP && go build -o pvf-mcp.exe ." -ForegroundColor Yellow
    exit 1
}

# ---- Install directory ----
if (-not $InstallDir) {
    $InstallDir = Join-Path $env:APPDATA "pvf-mcp"
}
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

$BinaryDest = Join-Path $InstallDir $BinaryName

Write-Host ""
Write-Host "[1/2] Installing binary" -ForegroundColor Yellow
Copy-Item -Force $BinarySrc $BinaryDest
$size = [math]::Round((Get-Item $BinaryDest).Length / 1MB, 1)
Write-Host "  [OK] $BinaryDest ($size MB)" -ForegroundColor Green

# ---- Detect tools ----
function Detect-Tools {
    $found = @()
    if (Test-Path "$env:USERPROFILE\.claude") { $found += "claude" }
    if (Test-Path "$env:USERPROFILE\.codex")  { $found += "codex" }
    # Cursor is always available as project-level install
    $found += "cursor"
    return $found
}

if ($Target -eq "generic") {
    if (-not $ConfigPath) {
        Write-Host "[ERROR] -ConfigPath required for --target generic" -ForegroundColor Red
        exit 1
    }
    $targets = @("generic")
}
elseif ($Target -and $Target -ne "all") {
    $targets = @($Target)
}
else {
    $targets = Detect-Tools
    if ($targets.Count -eq 0) {
        Write-Host "[WARN] No AI tools detected." -ForegroundColor Yellow
        Write-Host "Use -Target to specify: claude, cursor, codex, generic" -ForegroundColor Yellow
        exit 1
    }
}

if ($Target -eq "all") {
    $targets = Detect-Tools
}

Write-Host ""
Write-Host "[2/2] Configuring MCP: $($targets -join ', ')" -ForegroundColor Yellow

# ---- MCP config helper ----
$mcpEntry = @{
    command = $BinaryDest
}

function Write-McpConfig($ConfigFile, $ServersKey = "mcpServers") {
    $dir = Split-Path -Parent $ConfigFile
    New-Item -ItemType Directory -Force -Path $dir | Out-Null

    $config = @{}
    if (Test-Path $ConfigFile) {
        try {
            $config = Get-Content $ConfigFile -Raw -Encoding UTF8 | ConvertFrom-Json
        } catch {
            $config = @{}
        }
    }

    # ConvertFrom-Json returns PSCustomObject, convert to hashtable
    $ht = @{}
    foreach ($prop in $config.PSObject.Properties) {
        $ht[$prop.Name] = $prop.Value
    }

    if (-not $ht.ContainsKey($ServersKey)) {
        $ht[$ServersKey] = @{}
    }

    $servers = @{}
    foreach ($prop in $ht[$ServersKey].PSObject.Properties) {
        $servers[$prop.Name] = $prop.Value
    }
    $servers["pvf-mcp"] = $mcpEntry
    $ht[$ServersKey] = $servers

    # Write UTF-8 WITHOUT BOM — BOM breaks Claude Code's JSON parser
    $json = $ht | ConvertTo-Json -Depth 5
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($ConfigFile, $json, $utf8NoBom)
    Write-Host "  [OK] $ConfigFile" -ForegroundColor Green
}

foreach ($t in $targets) {
    switch ($t) {
        "claude" {
            # Claude Code may store MCP config in .claude.json (main state file)
            # or .claude/mcp.json (dedicated MCP config). Check both.
            $mainConfig = "$env:USERPROFILE\.claude.json"
            $altConfig  = "$env:USERPROFILE\.claude\mcp.json"
            if (Test-Path $mainConfig) {
                Write-McpConfig -ConfigFile $mainConfig -ServersKey "mcpServers"
            } else {
                Write-McpConfig -ConfigFile $altConfig -ServersKey "mcpServers"
            }
        }
        "cursor" {
            $projDir = if (Test-Path variable:Global:PWD) { $Global:PWD.Path } else { (Get-Location).Path }
            Write-McpConfig -ConfigFile "$projDir\.cursor\mcp.json" -ServersKey "mcpServers"
        }
        "codex" {
            Write-McpConfig -ConfigFile "$env:USERPROFILE\.codex\mcp.json" -ServersKey "mcpServers"
        }
        "generic" {
            Write-McpConfig -ConfigFile $ConfigPath -ServersKey "mcpServers"
        }
    }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Installation complete!" -ForegroundColor Green
Write-Host "Binary : $BinaryDest"
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Restart your AI coding tool"
Write-Host "  2. Open pvfUtility and load a PVF file"
Write-Host "  3. Ask your agent: 'run get_version to verify'"
Write-Host "========================================" -ForegroundColor Cyan
